
# Generated by Django 4.1.3 on 2022-11-12 04:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecollection',
            name='create_date',

            field=models.DateField(default=datetime.datetime(2022, 11, 12, 4, 5, 50, 363092, tzinfo=datetime.timezone.utc)),

            preserve_default=False,
        ),
    ]
