# Generated by Django 4.1.3 on 2022-11-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecollection',
            name='create_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
